# Generated by Django 3.1 on 2020-08-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isCompleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_description',
            field=models.CharField(default='Task Description', max_length=250),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(default='Task Name', max_length=100),
        ),
    ]
