# Generated by Django 3.1 on 2020-08-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_auto_20200808_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
