# Generated by Django 3.1 on 2020-08-09 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0003_auto_20200808_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date_created']},
        ),
    ]
