# Generated by Django 3.1 on 2020-08-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0004_auto_20200809_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='isCompleted',
            new_name='is_complete',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=100),
        ),
    ]
