# Generated by Django 3.1 on 2020-08-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0005_auto_20200811_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_description',
        ),
    ]
